# -*- coding: utf-8 -*-
"""Task1_Rainbow_Response_HF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-EkLf5CHt3BNTIAvNIMTL-Wkoj2muOVL
"""

!pip install transformers accelerate sentencepiece
!apt-get install -y graphviz

from transformers import pipeline
import graphviz
from IPython.display import Image, display

generator = pipeline("text2text-generation", model="google/flan-t5-small")

def generate_text(prompt, max_tokens=150):
    response = generator(prompt, max_new_tokens=max_tokens)
    return response[0]['generated_text']


rainbow = "Explain how a rainbow is formed in simple words."
rainbow_expl = generate_text(rainbow, max_tokens=150)

print("\nRainbow Explanation:\n")
print(rainbow_expl)

dot = graphviz.Digraph()
dot.attr(rankdir='TB', size="10,12", fontsize="20")
dot.attr('node', shape='box', fontsize='16', style='filled', fillcolor='lightblue')

dot.node("1", "Sunlight enters a raindrop")
dot.node("2", "Light bends (refraction)")
dot.node("3", "Light reflects inside")
dot.node("4", "Light exits & spreads")
dot.node("5", "Rainbow is seen")

dot.edges([("1", "2"), ("2", "3"), ("3", "4"), ("4", "5")])

dot.render("rainbow", format="png", cleanup=True)
display(Image("rainbow.png"))