# -*- coding: utf-8 -*-
"""Task2_Ocean_Poem_HF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kxaanzE7I8A-IULemysfEe8Dk6NSM9Fb
"""

!pip install transformers

from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

prompts = [
    "oceans",
]

for prompt in prompts:
    print(f"Prompt: {prompt}")
    output = generator(prompt, max_length=50, num_return_sequences=1)
    print(f"Generated Text: {output[0]['generated_text']}\n")
    print("-" * 60)